version: "3.6"
services:
  iris:
    build: .
    restart: always
    ports:
      - 51773
      - ${IRIS_PORT}:57777
      - 53773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app
